security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users:
            chain:
                providers: [normal, doctors]
        normal:
            entity:
                class: App\Entity\Users
                property: dni
        doctors:
            entity:
                class: App\Entity\Doctors
                property: dni

    encoders:
        App\Entity\Users:
            algorithm: bcrypt
            cost: 12
        App\Entity\Doctors:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path:   /logout
                target: /

            form_login:
                provider: users
                login_path: login
                check_path: login
                default_target_path: index
                username_parameter: login[dni]
                password_parameter: login[plainPassword]
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:

         #- { path: ^/test/db, roles: ROLE_USER }
         - { path: ^/appointments/, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/patient/, roles: ROLE_USER }
         - { path: ^/appointment/add, roles: ROLE_USER }
