index:
    path: /
    controller: App\Controller\AppController::index

login:
    path: /login
    controller: App\Controller\AppController::login

logout:
     path: /logout

addUser:
    path: /addUser
    controller: App\Controller\AppController::addUser
appointments:
    path: /patient/appointments
    controller: App\Controller\PatientController::index
date:
    path: /patient/date
    controller: App\Controller\PatientController::addAppointment
persistenceAppointment:
    path: /appointment/add
    controller: App\Controller\AppointmentController::persistAppointment