index:
    path: /
    controller: App\Controller\AppController::index

login:
    path: /login
    controller: App\Controller\AppController::login

logout:
     path: /logout

addUser:
    path: /addUser
    controller: App\Controller\AppController::addUser