index:
    path: /
    controller: App\Controller\AppController::index

login:
    path: /login
    controller: App\Controller\AppController::login

logout:
     path: /logout

addUser:
    path: /addUser
    controller: App\Controller\AppController::addUser
addDoctor:
    path: /addDoctor
    controller: App\Controller\AppController::addDoctor
appointments:
    path: /appointments/get
    controller: App\Controller\AppointmentController::getAppointments
generateAppointment:
    path: /patient/generateAppointment/
    controller: App\Controller\AppointmentController::generateAppointment
persistAppointment:
    path: /appointments/add/
    controller: App\Controller\AppointmentController::persistAppointment
removeAppointment:
    path: /appointments/remove
    controller: App\Controller\AppointmentController::removeAppointment