index:
    path: /
    controller: App\Controller\AppController::index

login:
    path: /login
    controller: App\Controller\AppController::login
logout:
     path: /logout
addUser:
    path: /addUser
    controller: App\Controller\AppController::addUser
addIncident:
    path: /addIncident
    controller: App\Controller\AppController::addIncident
addDoctor:
    path: /admins/addDoctor
    controller: App\Controller\AppController::addDoctor
getIncident:
    path: /admins/incidents/get
    controller: App\Controller\AppController::getIncident
getIncidents:
    path: /admins/incidents
    controller: App\Controller\AppController::getIncidents
addAnimal:
    path: /patients/addAnimal
    controller: App\Controller\AccountController::addAnimal
removeAnimal:
    path: /patients/removeAnimal
    controller: App\Controller\AccountController::removeAnimal
getAnimal:
    path: /patients/getAnimal
    controller: App\Controller\ProfileController::getAnimal
userProfile:
    path: /patients/profile/get
    controller: App\Controller\ProfileController::getPatient
searchDoctor:
    path: /patients/searchDoctor
    controller: App\Controller\SearchController::searchDoctor
getRecipes:
    path: /patients/getRecipes
    controller: App\Controller\RecipeController::getRecipes
addRecipe:
    path: /doctors/addRecipe
    controller: App\Controller\RecipeController::addRecipe
persistRecipe:
    path: /doctors/persistRecipe
    controller: App\Controller\RecipeController::persistRecipe
doctorProfile:
    path: /doctors/profile/get
    controller: App\Controller\ProfileController::getDoctor
closeAppointment:
    path: /doctors/appointments/close
    controller: App\Controller\AppointmentController::closeAppointments
persistCloseAppointment:
    path: /doctors/appoitments/persistClose
    controller: App\Controller\AppointmentController::persistCloseAppointments
account:
    path: /account/get
    controller: App\Controller\AccountController::getAccount
subscribe:
    path: /account/subscribe
    controller: App\Controller\AccountController::subscribe
unsubscribe:
    path: /account/unsubscribe
    controller: App\Controller\AccountController::unsubscribe
updateUser:
    path: /account/update
    controller: App\Controller\AccountController::update
appointments:
    path: /appointments/get
    controller: App\Controller\AppointmentController::getAppointments
oldAppointments:
    path: /appointments/getOld
    controller: App\Controller\AppointmentController::getOldAppointments
generateAppointment:
    path: /appointments/generate
    controller: App\Controller\AppointmentController::generateAppointment
generateVetAppointment:
    path: /appointments/vet/generate
    controller: App\Controller\AppointmentController::generateVetAppointment
persistAppointment:
    path: /appointments/add
    controller: App\Controller\AppointmentController::persistAppointment
removeAppointment:
    path: /appointments/remove
    controller: App\Controller\AppointmentController::removeAppointment
selectSpecialty:
    path: /appointments/specialty/select
    controller: App\Controller\AppointmentController::selectSpecialty

