index:
    path: /
    controller: App\Controller\AppController::index

login:
    path: /login
    controller: App\Controller\AppController::login
logout:
     path: /logout
addUser:
    path: /addUser
    controller: App\Controller\AppController::addUser
addIncident:
    path: /addIncident
    controller: App\Controller\AppController::addIncident
addDoctor:
    path: /admins/addDoctor
    controller: App\Controller\AppController::addDoctor
addAnimal:
    path: /patients/addAnimal
    controller: App\Controller\AccountController::addAnimal
removeAnimal:
    path: /patients/removeAnimal
    controller: App\Controller\AccountController::removeAnimal
getAnimal:
    path: /patients/getAnimal
    controller: App\Controller\ProfileController::getAnimal
userProfile:
    path: /patients/profile/get
    controller: App\Controller\ProfileController::getPatient
searchDoctor:
    path: /patients/searchDoctor
    controller: App\Controller\SearchController::searchDoctor
doctorProfile:
    path: /doctors/profile/get
    controller: App\Controller\ProfileController::getDoctor
account:
    path: /account/get
    controller: App\Controller\AccountController::getAccount
subscribe:
    path: /account/subscribe
    controller: App\Controller\AccountController::subscribe
unsubscribe:
    path: /account/unsubscribe
    controller: App\Controller\AccountController::unsubscribe
updateUser:
    path: /account/update
    controller: App\Controller\AccountController::update
appointments:
    path: /appointments/get
    controller: App\Controller\AppointmentController::getAppointments
generateAppointment:
    path: /appointments/generate
    controller: App\Controller\AppointmentController::generateAppointment
generateVetAppointment:
    path: /appointments/vet/generate
    controller: App\Controller\AppointmentController::generateVetAppointment
persistAppointment:
    path: /appointments/add
    controller: App\Controller\AppointmentController::persistAppointment
removeAppointment:
    path: /appointments/remove
    controller: App\Controller\AppointmentController::removeAppointment
selectSpecialty:
    path: /appointments/specialty/select
    controller: App\Controller\AppointmentController::selectSpecialty
